version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vishaka-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-vishaka}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-your-secure-password}
      POSTGRES_DB: ${DB_NAME:-vishaka}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-vishaka}"]
      interval: 5s
      timeout: 5s
      retries: 5

  matomo:
    image: matomo:apache
    container_name: vishaka-matomo
    restart: unless-stopped
    environment:
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_USER=matomo
      - MATOMO_DATABASE_PASSWORD=${MATOMO_DB_PASSWORD:-your-secure-password}
      - MATOMO_DATABASE_DBNAME=matomo
    volumes:
      - matomo_data:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mariadb:10.6
    container_name: vishaka-matomo-db
    restart: unless-stopped
    command: --max-allowed-packet=64MB
    environment:
      MYSQL_ROOT_PASSWORD: ${MATOMO_DB_ROOT_PASSWORD:-your-secure-root-password}
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo
      MYSQL_PASSWORD: ${MATOMO_DB_PASSWORD:-your-secure-password}
    volumes:
      - matomo_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  matomo_data:
  matomo_db:
