[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  # Runtime versions
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  
  # Database Configuration - Replace with your actual Neon DB URL
  DATABASE_URL = "postgresql://neondb_owner:npg_vn0YNk6fWlAj@ep-restless-cloud-afiwaqrj-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require"
  
  # JWT Authentication
  SECRET_KEY = "6pX9vQw3y$B&E)H@McQfTjWnZr4u7x!A"  # Generated secure key
  ALGORITHM = "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES = "1440"  # 24 hours
  
  # Application settings
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  
  # CORS and API settings
  BACKEND_CORS_ORIGINS = "*"  # Restrict this in production
  PROJECT_NAME = "Vishaka Vedic Astrology"
  API_V1_STR = "/api/v1"
  
  # Initial admin user - Change these in production
  FIRST_SUPERUSER = "admin@vishaka.astrology"
  FIRST_SUPERUSER_PASSWORD = "ChangeMe123!"
  
  # Swiss Ephemeris path
  SWISS_EPHEM_PATH = "./swiss_ephemeris"
  
  # Site URL
  NEXT_PUBLIC_SITE_URL = "https://vishaka-astrology.netlify.app"

# Redirect all API requests to the Netlify function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Handle SPA routing (for frontend)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["swisseph", "numpy", "pandas", "psycopg2-binary"]
  included_files = ["backend/**"]

[dev]
  command = "cd backend && uvicorn app.main:app --reload --port 8000"
  publish = "backend/app/static"
  targetPort = 8000
  port = 3000

# Build plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Required for Python functions
[functions]
  external_node_modules = ["swisseph", "numpy", "pandas", "psycopg2-binary"]
  included_files = ["backend/**"]

# Required for Python support
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["swisseph", "numpy", "pandas", "psycopg2-binary"]
  included_files = ["backend/**"]
  port = 3000
